### ISSUE TITLE
Создать файл с sql запросом на создание бд и 2 таблиц

### ISSUE THREAD

**Issue by SanyaWeber** [SanyaWeber/ChatGit#2]
Создать 2 таблицы:

Таблица User
ID(ai), firstname(varchar(255)), lastname(varchar(255)), login(varchar(255)), password(varchar(32)), is_deleted(boolean)

Таблица Message
ID(ai), user_id(связь с id из User), message(varchar(255)), is_deleted(boolean)

**Comment by stepandarya** [comment]
Реализовано
